name: syssec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - colorama
  - configobj
  - libusb
  - numpy
  - pyserial
  - tqdm
  - cython
  - ecpy
  - jupyter
  - matplotlib
  - nbstripout
  - make
  - holoviews
  - optuna
  - plotly
  - scipy
  - cmake
  - c-compiler
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/syssec
